version: "3.9"


services:
  web:
    container_name: web
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload && /app/start-reload.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
